version: '2'

services:
  webserver:
    build: ./docker/webserver
    image: phptest_web
    ports:
      - "90:80"
      - "443:443"
    volumes:
      - /Users/vanessahenson/projects/php/www:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=db_runwaytest

  ui:
    build: ./front-end-ui
    image: ui_webtest
    ports:
      - "80:4200"
